/// Flutter icons Momentumicon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Momentumicon
///      fonts:
///       - asset: fonts/Momentumicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Momentumicon {
  Momentumicon._();

  static const _kFontFam = 'Momentumicon';

  static const IconData approval = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow_left = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData banner = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bookmark = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData calender = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData camera = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData chat_1 = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData copy = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData deliver = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData icon_comission = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData icon_data_reseller = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData icon_delivery_order = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData icon_kelola_banner = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData icon_kelola_pegawai = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData icon_penjualan = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData icon_produk_toko = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData icon_status_pesanan = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData icon_tambah_produk = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData icon_ulasan_produk = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData icon_voucher_kupon = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData image = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData link = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData maps = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData out = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData qr = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData qr_check = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData reload = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData send = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData star = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData tick_square = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData trash = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData warehouse = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData warning = IconData(0xe824, fontFamily: _kFontFam);
}
